### ISSUE TITLE
Make backend serve the front-end files

### ISSUE THREAD

**Issue by TjenWellens** [osoc16/mijn-viaa#12]
Currently the static files are not accessible when the server would be deployed.

Add a 'static files' folder to the server so that: html, css, js, assets are accessible

**Comment by TjenWellens** [comment]
currently the whole app folder is statically served at url `/pages/`

this is a quick fix. The grunt file should be changed to make a public folder with all the public files in it.

**Comment by laurensdc** [comment]
Going to figure out how the deployment files should be organized when the important code is written.

**Comment by TjenWellens** [comment]
`app/views` contains templates which were the html files

**Comment by TjenWellens** [comment]
- [ ] serve a clean public folder instead of the whole app folder
