### ISSUE TITLE
Dashboard.js standardize api parsing

### ISSUE THREAD

**Issue by TjenWellens** [osoc16/mijn-viaa#15]
parseBarchart() is generic for all graphs -> use for all graphs
parseLineChart() is only for line chart -> remove

**Comment by laurensdc** [comment]
No longer an issue: parseLineChart() was removed, parseBarChart() is now a generic function renamed to drawChart() drawing x/y arrays

For drawing an object that's a keyValuePair as a piechart, function drawPieFromKvpObj() was added.
