### ISSUE TITLE
Handle 401 in front-end api calls

### ISSUE THREAD

**Issue by TjenWellens** [osoc16/mijn-viaa#16]
When an ajax call responds with a 401 error, a page refresh should be done. This way the page will be redirected to the login.

**Comment by laurensdc** [comment]
Try this code here (testing needed!) 

app.js

```
        if(r.readyState == 4 && r.status == 401) {   // No access
            window.location.replace('dashboard.html');
        }
```

![image](https://cloud.githubusercontent.com/assets/17620692/16846939/d1c3098c-49ee-11e6-9aa9-a3da6a7a1442.png)
