### ISSUE TITLE
Standardize API json format for error checking

### ISSUE THREAD

**Issue by TjenWellens** [osoc16/mijn-viaa#30]
[JSend format](https://labs.omniti.com/labs/jsend) for JSON responses
## Success

**Required keys:**
- status: Should always be set to "success".
- data: Acts as the wrapper for any data returned by the API call. If the call returns no data (as in the last example), data should be set to null.

```
{
    status : "success",
    data : { ... } | null
```
## Fail

When an API call is rejected due to invalid data or call conditions, the JSend object's data key contains an object explaining what went wrong, typically a hash of validation errors. 
**Required keys:**
- status: Should always be set to "fail".
- data: Again, provides the wrapper for the details of why the request failed. If the reasons for failure correspond to POST values, the response object's keys SHOULD correspond to those POST values.

```
{
    "status" : "fail",
    "data" : { ... } // details why failed
}
```
## Error

**Required keys:**
- status: Should always be set to "error".
- message: A meaningful, end-user-readable (or at the least log-worthy) message, explaining what went wrong.

**Optional keys:**
- code: A numeric code corresponding to the error, if applicable
## \- data: A generic container for any other information about the error, i.e. the conditions that caused the error, stack traces, etc.

```
{
    "status" : "error",
    "message" : "..."
}
```

**Comment by laurensdc** [comment]
At the moment, status code is checked.
If API call is finished but does not return 200, the status code will be returned with a generic error message. 

![image](https://cloud.githubusercontent.com/assets/17620692/16930795/12548410-4d3e-11e6-990e-ae23dd32eb9e.png)
