### ISSUE TITLE
Show current organisation on page

### ISSUE THREAD

**Issue by TjenWellens** [osoc16/mijn-viaa#54]
Maybe near the 'logged in' icon
- [x] backend
- [x] front-end

**Comment by TjenWellens** [comment]
Backend return `req.user.oNickname` in `js/available-services.js`

**Comment by TjenWellens** [comment]
route `/public/js/service-available.js` now returns:

``` js
var mijnVIAA = mijnVIAA || {};
mijnVIAA.isServiceAvailable = function (serviceName) {
  return {"MAM": 1, "AMS": 1, "FTP": 1}[serviceName];
};
mijnVIAA.getOrganisationName = function () {
  return "";
};
```

So use `mijnVIAA.getOrganisationName()` to get the name of the organisation in js-code on front-end

**Comment by laurensdc** [comment]
var available in every view now -> {{ orgName }} 
Deciding how we'll show it
