### ISSUE TITLE
Services links on front-end

### ISSUE THREAD

**Issue by TjenWellens** [osoc16/mijn-viaa#55]
- [x] FTP: 
  - link to zendesk article ?
  - launch external app: filezilla (or other ftp client) ?
- [x] DBS: (https://contract.viaa.be)
- [x] MAM (https://archief.viaa.be/)
- [x] AMS (http://registratie.viaa.be/)
- [x] #58 general 'Ask Permission' -> link to zendesk form

**Comment by brechtvdv** [comment]
DBS should be a link to https://contract.viaa.be

**Comment by laurensdc** [comment]
DBS c2c3e32

**Comment by laurensdc** [comment]
Linkd ftp to https://viaa.zendesk.com/hc/nl
