### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by laurensdc** [osoc16/mijn-viaa#6]
Implement them.

**Comment by igloosarecool** [comment]
Bedoel je breadcrumbs voor de navigatie? Is dit nodig in een site met slechts 2 niveau's?

**Comment by laurensdc** [comment]
Goed punt, zit er nu in alleen bij services. Ik observeer mijn eigen browsegedrag steeds zo goed ik kan, en ik merk dat ik al klik op de breadcrumb ipv het menu-item (terug naar services gaan).

Kunnen we dit usertesten en adh daarvan beslissen of we hem weg doen?

**Comment by laurensdc** [comment]
Ook te overleggen of de services niet directer bereikbaar moeten zijn -> Vb onder services ze alle4 weergeven in submenu / zijbalk menu / hover menu (ik vote alleszins tegen hover)
