### ISSUE TITLE
Return error when ajax call failed

### ISSUE THREAD

**Issue by Dobbelsteen** [osoc16/mijn-viaa#9]
When the Ajax call fails on the mainpage, the preloader keeps "loading" and the error message is only returned in the console. 
On the other pages it's the same thing (no feedback if the API is down)
It would be nice to have a pop-up or something to give the user feedback when the API services don't work (which shouldn't happen in an ideal world, but crap happens)

**Comment by laurensdc** [comment]
Error messages & their display in the views to be reviewed.
